controllers.checkIn:
  resource: ../../src/CheckIn/Communication/Controller/
  type: annotation

controllers.checkOut:
  resource: ../../src/CheckOut/Communication/Controller/
  type: annotation

controllers.parkingStatus:
  resource: ../../src/ParkingStatus/Communication/Controller/
  type: annotation
