controllers.parker:
  resource: ../../src/Parker/Communication/Controller/
  type: annotation

controllers.checkIn:
  resource: ../../src/CheckIn/Communication/Controller/
  type: annotation

controllers.parkingStatus:
  resource: ../../src/ParkingStatus/Communication/Controller/
  type: annotation
