version: '1.0'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - '8080:80'
    volumes:
      - ../:/var/www/php
    networks:
      - nginx
    depends_on:
      - php
      - mysql

  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    restart: unless-stopped
    environment:
      APP_ENV: dev
      DATABASE_URL: mysql://root:password@mysql:3306/Parkhaus?serverVersion:8.0
    volumes:
      - ../:/var/www/php
    networks:
      - nginx
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: Parkhaus
    ports:
      - "3306:3306"
    networks:
      - nginx
    volumes:
      - ./mysql/setup_database.sql:/docker-entrypoint-initdb.d/setup_database.sql

networks:
  nginx:

